### ISSUE TITLE
Update all mod screenshots

### ISSUE THREAD

**Issue by damionvega** [anymod/guide#12]
The master mods were updated and the screenshots throughout the app need to reflect the changes.

**Comment by tyrw** [comment]
Did you have screenshots in mind for the AnyMod guide, or was this intended to mean go through and see if there are any screenshots that are out of date?

**Comment by damionvega** [comment]
We need up to date screenshots via https://github.com/anymod/uf-docs/issues/4

**Comment by tyrw** [comment]
I'm not able to tell how that answers the question -- can you please answer it directly?

**Comment by damionvega** [comment]
The latter: we need to go through the guide and update any images that are out of date.

**Comment by tyrw** [comment]
Ok, I don't think there will be any so I'm closing this
